<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "bigelowv_admin");
if (!defined("PJ_PASS")) define("PJ_PASS", "_eJE1%a7g&g)");
if (!defined("PJ_DB")) define("PJ_DB", "bigelowv_site");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/admin/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/home/bigelowva/public_html/admin/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "http://bigelowvacationrentals.com/admin/");
if (!defined("PJ_SALT")) define("PJ_SALT", "OMSY4TRO");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "OTkxNDk5ODMzOTUxOTEzMTk5MTg5ODQxODkzNTU1MTQ5NTkxMDg3MDc4MjMwNTM5MDE1MTkwNDYwNTQ1MTMyNzU1NDkwMTcyNDk3NjUzOTg3Mjg4NDg3MDY0ODYwNzAwMTgzIDgzNDc0MjMyMzQ3Njg0NzE1NDc5NzE2NzE0MDcwOTQ2MjcyNDA2OTMwMjc5NzI2MjcxNzMyNDgzOTY3Nzg2MjMwOTAyMzI0MTYzNTYyNjc5NTI3MzgyOTQ0NTI2NDQ0MjY2NyAxMDMyNTkwOTcyNTU3NTE0ODkwNzY5MTI3NDE3NTQzNTMxMDM0NjcyMTA0NTU3MTU4ODU4NDg2MzEzODg1NjYxMjE2NzM0ODA0NTY3NzQ4ODcwNTg0MzQyNTYyMjIwNjA4ODU0IDM1OTIwNTYzODcxMzA0ODE2OTg1MjA3Mzk3MjIzNDIyMzEwNDM5OTUxMDcyOTAzMjA5NjY1NDYyNDAxNTM3NTM1NTYyNTM5NTc1NDA2MDMwOTg4Mjg0MDA0NDMxNTIwNTU1OSA1NTI0NDM2ODI3NjkwOTE2MjA1NTg5MTA5MDIxMDkxMDcwOTk4NjM4ODE3NTg5Mzk5NTk5NjAyNDk3NjQ1OTkwOTcxOTYwNjQ0MzY4MDMwMDE0NzM1NjQ3NjQ2NTY5NzEyMDUgNDc5MDM2OTkzNDU4ODYzNDQ1OTc2OTg0OTk2NjY5MjkxMjM1MDYyNTg1ODgwOTAxMTgxNzgzMjUyODczOTYxODk1MDI4Mzc1MDI1MTAxMjE3MzYxMTUxOTUwMzA1NjMzNTE4IDgyNjAzMDc3MzE4MTMwMDMzODA4NDA1MTEwMDAyMzgwNzEwNTM4MzI2MDIxMTg1NDQ3NjU1NDI1ODAwMjU3MzI4MDAyNTQyMDkyMTMxMjY2NjM3NTMzOTA1NjkyMTc2NzU0IDEwNjIxODk1MzMxMzk1OTEyMjMxNDgwMTA1NjE4ODk5Nzc3NDU2MjgyMDI1ODg3MDU1MjMyMzE4MzUyOTQ2ODE4ODEwMTYxMDI0NjY1MDA2NDQ4ODk4NDMwNjU4MzA4MDY2MTMgMTg1NzMzNDQ2NjIxNTc4NzM0OTQ2MTA2OTMzNjY4OTY2MDQ5MDk1MDI2MDA2OTI5MzgyODUxNzMxMjI3NDU0MzI2MDUzNDI5Mjc2NDg4ODI1MDA5ODA1ODg2NDY0NDYxNTE4");
?>